### ISSUE TITLE
Kubernetes modules do not support multiple kubeconfig files in KUBECONFIG

### ISSUE THREAD

**Issue by larsks** [ansible-collections/kubernetes.core#544] opened 2022-11-24 00:19 UTC
##### SUMMARY

`kubectl` treats the `KUBECONFIG` environment variable as a PATH-style variable: a `:` delimited list of files in which to find kubernetes client configurations. In other words, this is both supported and relatively common:

```
KUBECONFIG=/path/to/kubeconfig1:/path/to/kubeconfig2
```

This is in fact documented in the [official documentation](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#set-the-kubeconfig-environment-variable).

Unfortunately, the `kubernetes.core` modules appear to only use the first component of the path, causing surprising failures when attempting to implement successful command lines using `k8s`, `k8s_info`, etc.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- `kubernetes.core.k8s`
- `kubeneretes.core.k8s_info`

...probably others.

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.6]
  config file = None
  configured module search path = ['/home/lars/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lars/.local/pipx/venvs/ansible/lib64/python3.11/site-packages/ansible
  ansible collection location = /home/lars/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/lars/.local/bin/ansible
  python version = 3.11.0 (main, Oct 24 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/lars/.local/pipx/venvs/ansible/lib64/python3.11/site-packages/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.3.2  

# /home/lars/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.3.2  

# /home/lars/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.3.2  
```

##### CONFIGURATION

```paste below
...no output...
```

##### STEPS TO REPRODUCE

Given the following playbook:

```yaml
- hosts: localhost
  gather_facts: false
  collections:
    - kubernetes.core
  tasks:
    - k8s_info:
        api_version: v1
        kind: Node
      register: nodes

    - debug:
        var: nodes
```

Run it like this:

```
KUBECONFIG=/dev/null:$HOME/.kube/config ansible-playbook playbook.yaml
```

Compare that with:

```
KUBECONFIG=/dev/null:$HOME/.kube/config kubectl get nodes
```

##### EXPECTED RESULTS

I expect the Ansible kubernetes modules to implement the same config file handling used by `kubectl`.

##### ACTUAL RESULTS

```paste below
TASK [k8s_info] ***************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to load kubeconfig due to Invalid kube-config. /dev/null file is empty"}
```

**Comment by abikouo** [comment] 2022-11-24 16:16
@larsks The issue is not related to the Kubernetes collection but to the Kubernetes python client which read and YAML parses each file from the `KUBECONFIG` environment variable and raises an error if the file is empty

https://github.com/kubernetes-client/python/blob/d0df4694bed0052b33bac84aadb754bdf99aae66/kubernetes/base/config/kube_config.py#L712-L719

This issue should be raised on that python module.
Please also note that you are using the `KUBECONFIG` environment variable whereas Kubernetes ansible uses `K8S_AUTH_KUBECONFIG` which is quite the same but specific to Ansible.

**Comment by gravesm** [comment] 2022-11-28 15:45
I'm going to close this as there's nothing we can do about it in the collection. As @abikouo pointed out, the problem will need to be fixed in the python kubernetes client.

**Closed by gravesm** 2022-11-28 15:45 UTC
Labels: verified
