### ISSUE TITLE
Unable to create AWX Instance: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS

### ISSUE THREAD

**Issue by andrewvillano** [ansible-collections/kubernetes.core#543] opened 2022-11-18 14:41 UTC
##### SUMMARY

I am at the point here: https://github.com/ansible/awx-operator

Where I:" Finally, run kustomize again to create the AWX instance in your cluster:"

However, I receive the following error message:
TASK [Get information about the cluster] ********************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'k8s'. Error was a <class 'ValueError'>, original message: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS"}

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/andrew/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/andrew/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.13 (default, Jun 14 2022, 17:49:07) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 2.11.3
  libyaml = True

```

##### COLLECTION VERSION

```# /usr/lib/python3.8/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 4.5.0  

```

##### CONFIGURATION

```[andrew@aphros AWX]$ ansible-config dump --only-changed
[andrew@aphros AWX]$ 

```

##### OS / ENVIRONMENT

RHEL 8

##### STEPS TO REPRODUCE

```Follow steps here: https://github.com/ansible/awx-operator

leading up to : ./kustomize build . | kubectl apply -f -

```

##### EXPECTED RESULTS

Expected playbook to build node.

##### ACTUAL RESULTS

```
kubectl logs -f deployments/awx-operator-controller-manager -c awx-manager

An unhandled exception occurred while running the lookup plugin 'k8s'. Error was a <class 'ValueError'>, original message: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS\
```

**Comment by moducker** [comment] 2022-11-23 17:57
@andrewvillano any update? I'm currently experiencing the same thing on a FIPS OS, working down the rabbithole - but I currently don't see anywhere that MD5 is being used.

**Comment by andrewvillano** [comment] 2022-11-28 14:06
I haven’t heard anything as of yet.



[EASTERN DISTRICT OF NEW YORK_color3]
Mr. Andrew V. Villano , CCNA, RHCSA
Linux Administrator
United States District Court
225 Cadman Plaza East, Room 304S
Brooklyn, NY 11201-1818
(718) 613 - 2682
***@***.******@***.***>

***@***.***  ***@***.***

**Comment by gravesm** [comment] 2022-11-28 15:27
Could you provide the version of ansible and the version of the kubernetes.core collection you are using?

**Comment by andrewvillano** [comment] 2022-11-28 15:58
ansible [core 2.12.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/andrew/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /home/andrew/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.13 (default, Jun 14 2022, 17:49:07) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 2.11.3
  libyaml = True

$ ansible-galaxy collection list | grep kubernetes
community.kubernetes          2.0.1  
kubernetes.core               2.2.3  
[andrew@nyed-aphros ~]$

**Comment by moducker** [comment] 2022-11-28 16:03
My versions differ from OPs, but same issue:

ansible [core 2.12.10]
community.kubernetes          2.0.1
kubernetes.core               2.3.2

It seems like something in the K8S lookup related to creating a secret is using MD5. I get the same error ([digital envelope routines: EVP_DigestInit_ex] disabled for FIPS) if I try to hash a file with openssl MD5 in FIPS mode.

**Comment by ravitejb** [comment] 2023-02-17 01:09
is there any update on this? I'm also having the same issue..

I'm running k8s on RHEL8 FIPS enabled nodes. installed awx-operator and while installing the AWX i get this error.

```
--------------------------- Ansible Task StdOut -------------------------------

TASK [Create imagePullSecret] **************************************************
task path: /opt/ansible/playbooks/awx.yml:17

-------------------------------------------------------------------------------
{"level":"error","ts":1676595672.1635306,"logger":"logging_event_handler","msg":"","name":"awx","namespace":"awx","gvk":"awx.ansible.com/v1beta1, Kind=AWX","event_type":"runner_on_failed","job":"1586238546790351251","EventData.Task":"Get information about the cluster","EventData.TaskArgs":"","EventData.FailedTaskPath":"/opt/ansible/roles/common/tasks/main.yml:3","error":"[playbook task failed]","stacktrace":"github.com/operator-framework/operator-sdk/internal/ansible/events.loggingEventHandler.Handle\n\t/workspace/internal/ansible/events/log_events.go:111"}

--------------------------- Ansible Task StdOut -------------------------------

 TASK [Get information about the cluster] ********************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'k8s'. Error was a <class 'ValueError'>, original message: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS"}

```

**Comment by gravesm** [comment] 2023-02-17 13:59
Please see my last comment. Since version 2.0.0 of the collection every use of md5 has been replaced with sha256. I just grepped the entire collection to double check. I am going to close this issue as I don't believe there is anything to do here. My guess would be that you are using an old version of awx-operator.

If someone can provide a minimal playbook that reproduces the error using the latest version of the collection, I'm happy to reopen and investigate.

**Closed by gravesm** 2023-02-17 13:59 UTC
Labels: needs_info
