### ISSUE TITLE
k8s_info module fails with  TypeError: 'ResourceField' has no length

### ISSUE THREAD

**Issue by jakrol** [ansible-collections/kubernetes.core#447] opened 2022-05-02 11:18 UTC
##### SUMMARY
k8s_info module fails with  TypeError: 'ResourceField' has no length. Tested with different resource kinds.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
k8s_info

##### ANSIBLE VERSION
```paste below
ansible [core 2.11.7]
  config file = /home/user/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.venv/lib/python3.8/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.venv/bin/ansible
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/user/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 2.3.0

# /home/user/.venv/lib/python3.8/site-packages/ansible_collections
Collection      Version
--------------- -------
kubernetes.core 1.2.1
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(/home/user/ansible.cfg) = False
ANSIBLE_NOCOWS(/home/user/ansible.cfg) = True
DEFAULT_FILTER_PLUGIN_PATH(/home/user/ansible.cfg) = ['/home/user/.ansible/plugins/filter', '/usr/share/ansible/plugins/filter'/>
DEFAULT_FORKS(/home/user/ansible.cfg) = 100
DEFAULT_HASH_BEHAVIOUR(/home/user/ansible.cfg) = replace
DEFAULT_LOOKUP_PLUGIN_PATH(/home/user/ansible.cfg) = ['/home/user/.ansible/plugins/lookup', '/usr/share/ansible/plugins/lookup'/>
DEFAULT_REMOTE_USER(/home/user/ansible.cfg) = core
DEFAULT_TIMEOUT(/home/user/ansible.cfg) = 180
DIFF_ALWAYS(/home/user/ansible.cfg) = True
DISPLAY_SKIPPED_HOSTS(/home/user/ansible.cfg) = True
INVENTORY_ENABLED(/home/user/ansible.cfg) = ['host_list', 'script', 'auto', 'yaml', 'ini']
INVENTORY_IGNORE_EXTS(/home/user/ansible.cfg) = ['{{(REJECT_EXTS + (‘.orig’', '‘.cfg’', '‘.retry’))}}']
```

##### OS / ENVIRONMENT
Controller:
```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
Target host:
```
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=2905.2.1
VERSION_ID=2905.2.1
BUILD_ID=2021-08-03-2015
PRETTY_NAME="Flatcar Container Linux by Kinvolk 2905.2.1 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar-linux.org/"
BUG_REPORT_URL="https://issues.flatcar-linux.org"
FLATCAR_BOARD="amd64-usr"
```

```
python3 --version
Python 3.8.12 (9ef55f6fc369, Oct 24 2021, 20:11:54)
[PyPy 7.3.7 with GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

```
pip3 freeze
cachetools==5.0.0
certifi==2021.10.8
cffi==1.14.6
charset-normalizer==2.0.11
docker==5.0.3
docker-pycreds==0.4.0
google-auth==2.6.6
greenlet==0.4.13
hpy==0.0.3
idna==3.3
kubernetes==23.3.0
oauthlib==3.2.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
python-dateutil==2.8.2
python-string-utils==1.0.0
PyYAML==6.0
readline==6.2.4.1
requests==2.27.1
requests-oauthlib==1.3.1
rsa==4.8
six==1.16.0
urllib3==1.26.8
websocket-client==1.2.3
```

##### STEPS TO REPRODUCE

```yaml
- name: Read pods
      kubernetes.core.k8s_info:
        kind: Pod
        kubeconfig: /home/user/kubeconfig.conf
  register: pods

- debug: var=pods
```

##### EXPECTED RESULTS

List of pods

##### ACTUAL RESULTS

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/home/core/.ansible/tmp/ansible-tmp-1651492036.1053739-6013-277344940983970/AnsiballZ_k8s_info.py", line 100, in <module>
    _ansiballz_main()
  File "/home/core/.ansible/tmp/ansible-tmp-1651492036.1053739-6013-277344940983970/AnsiballZ_k8s_info.py", line 92, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/core/.ansible/tmp/ansible-tmp-1651492036.1053739-6013-277344940983970/AnsiballZ_k8s_info.py", line 41, in invoke_module
    run_name='__main__', alter_sys=True)
  File "/home/core/ansible_python_bootstrap/pypy3.8-v7.3.7-linux64/lib/pypy3.8/runpy.py", line 210, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/home/core/ansible_python_bootstrap/pypy3.8-v7.3.7-linux64/lib/pypy3.8/runpy.py", line 98, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/core/ansible_python_bootstrap/pypy3.8-v7.3.7-linux64/lib/pypy3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_kubernetes.core.k8s_info_payload_o1id7i_h/ansible_kubernetes.core.k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_info.py", line 209, in <module>
  File "/tmp/ansible_kubernetes.core.k8s_info_payload_o1id7i_h/ansible_kubernetes.core.k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_info.py", line 205, in main
  File "/tmp/ansible_kubernetes.core.k8s_info_payload_o1id7i_h/ansible_kubernetes.core.k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s_info.py", line 171, in execute_module
  File "/tmp/ansible_kubernetes.core.k8s_info_payload_o1id7i_h/ansible_kubernetes.core.k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 407, in kubernetes_facts
  File "/tmp/ansible_kubernetes.core.k8s_info_payload_o1id7i_h/ansible_kubernetes.core.k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 375, in find_resource
  File "/tmp/ansible_kubernetes.core.k8s_info_payload_o1id7i_h/ansible_kubernetes.core.k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 361, in _find_resource_with_prefix
  File "/tmp/ansible_kubernetes.core.k8s_info_payload_o1id7i_h/ansible_kubernetes.core.k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/client/discovery.py", line 159, in get
  File "/home/core/ansible_python_bootstrap/pypy3.8-v7.3.7-linux64/lib/pypy3.8/site-packages/kubernetes/dynamic/discovery.py", line 242, in search
    results = self.__search(self.__build_search(**kwargs), self.__resources, [])
  File "/home/core/ansible_python_bootstrap/pypy3.8-v7.3.7-linux64/lib/pypy3.8/site-packages/kubernetes/dynamic/discovery.py", line 276, in __search
    return self.__search(parts[1:], resourcePart, reqParams + [part] )
  File "/home/core/ansible_python_bootstrap/pypy3.8-v7.3.7-linux64/lib/pypy3.8/site-packages/kubernetes/dynamic/discovery.py", line 290, in __search
    matches.extend(self.__search([key] + parts[1:], resources, reqParams))
  File "/home/core/ansible_python_bootstrap/pypy3.8-v7.3.7-linux64/lib/pypy3.8/site-packages/kubernetes/dynamic/discovery.py", line 276, in __search
    return self.__search(parts[1:], resourcePart, reqParams + [part] )
  File "/home/core/ansible_python_bootstrap/pypy3.8-v7.3.7-linux64/lib/pypy3.8/site-packages/kubernetes/dynamic/discovery.py", line 266, in __search
    prefix, group, part, resourcePart.preferred)
  File "/tmp/ansible_kubernetes.core.k8s_info_payload_o1id7i_h/ansible_kubernetes.core.k8s_info_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/client/discovery.py", line 132, in get_resources_for_api_version
TypeError: 'ResourceField' has no length
fatal: [testhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "kind": "Pod",
        "kubeconfig": "/home/user/kubeconfig.conf",
        "module_args": {
            "kind": "Pod",
            "kubeconfig": "/home/user/kubeconfig.conf"
        }
    },
```

**Comment by gravesm** [comment] 2022-05-11 15:10
@jakrol I have tried and am unable to reproduce this problem. I also looked through the code involved for anything obvious, and nothing sticks out. We would need some way to reproduce this before we can fix it.

**Comment by lazyfrosch** [comment] 2022-11-07 15:44
In my case this fails with the following stacktrace:

<details>
<summary>Details</summary>

```
Traceback (most recent call last):
  File "/home/core/.ansible/tmp/ansible-tmp-1667834884.668694-69019-65093378595382/AnsiballZ_k8s.py", line 107, in <module>
    _ansiballz_main()
  File "/home/core/.ansible/tmp/ansible-tmp-1667834884.668694-69019-65093378595382/AnsiballZ_k8s.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/core/.ansible/tmp/ansible-tmp-1667834884.668694-69019-65093378595382/AnsiballZ_k8s.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.kubernetes.core.plugins.modules.k8s', init_globals=dict(_module_fqn='ansible_collections.kubernetes.core.plugins.modules.k8s', _modlib_path=modlib_path),
  File "/opt/bin/pypy3/lib/pypy3.9/runpy.py", line 213, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/opt/bin/pypy3/lib/pypy3.9/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/opt/bin/pypy3/lib/pypy3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_kubernetes.core.k8s_payload_n4d35fko/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py", line 486, in <module>
  File "/tmp/ansible_kubernetes.core.k8s_payload_n4d35fko/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py", line 482, in main
  File "/tmp/ansible_kubernetes.core.k8s_payload_n4d35fko/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/modules/k8s.py", line 459, in execute_module
  File "/tmp/ansible_kubernetes.core.k8s_payload_n4d35fko/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 797, in execute_module
  File "/tmp/ansible_kubernetes.core.k8s_payload_n4d35fko/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 375, in find_resource
  File "/tmp/ansible_kubernetes.core.k8s_payload_n4d35fko/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/common.py", line 360, in _find_resource_with_prefix
  File "/tmp/ansible_kubernetes.core.k8s_payload_n4d35fko/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/client/discovery.py", line 159, in get
  File "/opt/bin/pypy3/lib/pypy3.9/site-packages/kubernetes/dynamic/discovery.py", line 242, in search
    results = self.__search(self.__build_search(**kwargs), self.__resources, [])
  File "/opt/bin/pypy3/lib/pypy3.9/site-packages/kubernetes/dynamic/discovery.py", line 276, in __search
    return self.__search(parts[1:], resourcePart, reqParams + [part] )
  File "/opt/bin/pypy3/lib/pypy3.9/site-packages/kubernetes/dynamic/discovery.py", line 290, in __search
    matches.extend(self.__search([key] + parts[1:], resources, reqParams))
  File "/opt/bin/pypy3/lib/pypy3.9/site-packages/kubernetes/dynamic/discovery.py", line 276, in __search
    return self.__search(parts[1:], resourcePart, reqParams + [part] )
  File "/opt/bin/pypy3/lib/pypy3.9/site-packages/kubernetes/dynamic/discovery.py", line 265, in __search
    resourcePart.resources = self.get_resources_for_api_version(
  File "/tmp/ansible_kubernetes.core.k8s_payload_n4d35fko/ansible_kubernetes.core.k8s_payload.zip/ansible_collections/kubernetes/core/plugins/module_utils/client/discovery.py", line 125, in get_resources_for_api_version
TypeError: 'ResourceField' has no length
```

</details>

The code in question:

https://github.com/ansible-collections/kubernetes.core/blob/b967b55a16243ea1bdf3279716bb863f3cbf46f4/plugins/module_utils/client/discovery.py#L125-L133

The error is raised during parsing of API resources from `/api/v1`, in my case for the kind:

```
{'kind': 'Binding',
 'name': 'bindings',
 'namespaced': True,
 'singularName': '',
 'verbs': ['create']}
```

Digging deeper into what the problem could be.

**Comment by lazyfrosch** [comment] 2022-11-07 16:43
This seems to be a PyPy compatibility issue...

`resource` is of type `ResourceField` coming directly from the API client, this is basically a wrapper around using `object` as a dict.

Does not work:
```
**resource
```

Works:
```
**resource.__dict__
```

Any Python guru wants to chip in?

**Comment by lazyfrosch** [comment] 2022-11-07 16:45
For the sake of completeness:
```
# cat /etc/os-release
NAME="Flatcar Container Linux by Kinvolk"
ID=flatcar
ID_LIKE=coreos
VERSION=3227.2.4
VERSION_ID=3227.2.4
BUILD_ID=2022-10-27-1321
SYSEXT_LEVEL=1.0
PRETTY_NAME="Flatcar Container Linux by Kinvolk 3227.2.4 (Oklo)"
ANSI_COLOR="38;5;75"
HOME_URL="https://flatcar.org/"
BUG_REPORT_URL="https://issues.flatcar.org"
FLATCAR_BOARD="amd64-usr"
CPE_NAME="cpe:2.3:o:flatcar-linux:flatcar_linux:3227.2.4:*:*:*:*:*:*:*"

# python -V
Python 3.9.12 (05fbe3aa5b0845e6c37239768aa455451aa5faba, Mar 29 2022, 08:15:34)
[PyPy 7.3.9 with GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
```

**Comment by lazyfrosch** [comment] 2022-11-07 17:35
Here is a gist that shows the Pypy erroneous behavior:
https://gist.github.com/lazyfrosch/2e9cb973e83bec4bb8d6d6e9ed48a723

**Comment by lazyfrosch** [comment] 2022-11-07 17:41
Pypy issue: https://foss.heptapod.net/pypy/pypy/-/issues/3841

**Comment by gravesm** [comment] 2022-11-07 17:55
Thanks, @lazyfrosch. I can confirm that I'm able to reproduce this using pypy. I'm going to close this issue as this is not a bug with the collection.

**Closed by gravesm** 2022-11-07 17:55 UTC
Labels: needs_verify
