### ISSUE TITLE
validate_certs: false for helm plugin writes out new kubeconfig

### ISSUE THREAD

**Issue by akamac** [ansible-collections/kubernetes.core#542] opened 2022-11-10 06:45 UTC
As per [code](https://github.com/ansible-collections/kubernetes.core/blob/b967b55a16243ea1bdf3279716bb863f3cbf46f4/plugins/module_utils/helm.py#L49), if one sets `validate_certs: false` for helm plugins, it leads to the generation of a new kubeconfig.
My use case is to override host value from the existing kubeconfig (with `host:` or `K8S_AUTH_HOST`) and skip tls verification (`K8S_AUTH_VERIFY_SSL: false`) due to CN mismatch, caused by host override.
Currently, due to code logic, kubeconfig's context is wiped out and I cannot authorise.

**Comment by gravesm** [comment] 2022-11-10 13:26
Duplicate of #538

**Closed by gravesm** 2022-11-10 13:26 UTC
